<!DOCTYPE html>
<html lang="ru">
	<meta charset="UTF-8">
	<title>Вход</title>
	<link rel="stylesheet" type="text/css" href="/css/reg_style.css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
</head>
<body>
	<div class="top">
            <div class="home">БЛОГ</div>
		<div class="authBox">
			<div class="regist"><a href="/user/register">РЕГИСТРАЦИЯ</a></div>
		</div>
	</div>
	<div class="wrapper">
		<form method="POST" action="/user/login">
			<div class="topAuth">
				<h3>Авторизация</h3>
			</div>
			<div class="formBody">
                            <div class="uncorrectPass">
                                <?php if ($this->error): ?>
                                    <?=$this->error?>
                                <?php endif; ?>
                            </div>
				<div class="logPassWrapper">
					<div class="labelBox">
						<label for="email">Email</label>
						<label for="password">Пароль</label>
					</div>
					<div class="inputBox">
						<input type="text" class="inputLog" name="email" id="email" placeholder="Введите email"/>
						<input type="password" name="password" id="password" placeholder="Введите пароль"/>
					</div>	
				</div>
				<button type="submit" name="submit">Войти</button>
			</div>		
		</form>
	</div>
</body>
</html>